title: "aaa"
summary: "クレジットカードによる決済は日常となっていますが、その仕組みを理解することは困難です。そこで，シンプルな決済ネットワークをGo(?)を用いて実装することによって，クレジットカードをスキャンしてから買い物が成立するまでに何が起きているのかを理解することを目的とします。"
topics: []
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - network-overview
  - network-protocol
  - card-create
  - iso8583-implement
  - issuer-network-implement
  - acquirer-network-implement
  - end

